
%--------------------------------------------------------------------------
% Housekeeping
%--------------------------------------------------------------------------

clear all; clc; pause(0.01), randn('seed',3212), rand('seed',3212), warning off

% Question 1:
% Upload the train and test data

TrainData = readtable('DataReturnsPredictability.xlsx','Sheet',1,'ReadVariableNames',true);
TestData  = readtable('DataReturnsPredictability.xlsx','Sheet',2,'ReadVariableNames',true);

% Question 1:

% Estimate a simple predictive regression by using least squares and
% The prediction can be simply generated by using the TestData
% The MSE should be computed based on the test data

% you can use the command "fitlm"

Mdl         = fitlm(TrainData(:,2:end)); % estimate the model using the training data 
OLSforecast = [ones(size(TestData.ExReturns,1),1) table2array(TestData(:,2:end-1))]*table2array(Mdl.Coefficients(:,1)); %forecast based on test data
OLSmse      = 100*mean((TestData.ExReturns - OLSforecast).^2);

% Question 2:

% Estimate a simple predictive regression by using a Ridge regression model and
% The prediction can be simply generated by using the TestData
% The MSE should be computed based on the test data

% you can use the command "ridge"

lambda = 0:1e-5:5e-3;
B = ridge(TrainData.ExReturns,table2array(TrainData(:,2:end-1)),lambda);

%etc... 
